"""
Download Lichess puzzle database -> filter -> export benchmark_positions.txt
"""
import csv
import io
import os
import sys
import urllib.request
import zstandard

import chess

PUZZLE_URL = "https://database.lichess.org/lichess_db_puzzle.csv.zst"
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "res")
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "benchmark_positions.txt")

TACTICAL_THEMES = {
    "fork", "pin", "discoveredAttack", "discoveredCheck",
    "sacrifice", "attraction", "deflection", "interference",
    "skewer", "doubleCheck", "xRayAttack", "intermezzo",
    "clearance", "capturingDefender", "trappedPiece",
    "hangingPiece", "exposedKing", "promotion",
}

EXCLUDE_THEMES = {"mateIn1", "oneMove"}
PREFER_NON_ENDGAME = True

def parse_args():
    args = {
        "count": 30,
        "min_rating": 1500,
        "max_rating": 2000,
        "min_popularity": 80,
    }
    for arg in sys.argv[1:]:
        if arg.startswith("--count="):
            args["count"] = int(arg.split("=", 1)[1])
        elif arg.startswith("--min-rating="):
            args["min_rating"] = int(arg.split("=", 1)[1])
        elif arg.startswith("--max-rating="):
            args["max_rating"] = int(arg.split("=", 1)[1])
        elif arg.startswith("--min-popularity="):
            args["min_popularity"] = int(arg.split("=", 1)[1])
    return args

def stream_csv_from_url(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    response = urllib.request.urlopen(req)

    decompressor = zstandard.ZstdDecompressor()
    stream_reader = decompressor.stream_reader(response)

    text_stream = io.TextIOWrapper(stream_reader, encoding="utf-8")
    reader = csv.reader(text_stream)

    headers = next(reader, None)
    if headers is None:
        raise RuntimeError("Empty CSV")
    return headers, reader

def passes_filter(row, headers, args):
    idx = {h: i for i, h in enumerate(headers)}

    rating = int(row[idx["Rating"]])
    popularity = int(row[idx["Popularity"]])
    themes = row[idx["Themes"]]
    moves = row[idx["Moves"]]

    if not (args["min_rating"] <= rating <= args["max_rating"]):
        return False
    if popularity < args["min_popularity"]:
        return False

    theme_set = set(themes.split())
    if theme_set & EXCLUDE_THEMES:
        return False
    if not (theme_set & TACTICAL_THEMES):
        return False

    num_total = len(moves.split())
    player_moves = num_total // 2
    if not (2 <= player_moves <= 3):
        return False

    if PREFER_NON_ENDGAME and "endgame" in theme_set:
        return False

    return True

def uci_to_benchmark_move(uci):
    return uci

def write_benchmark(pos_id, fen, best_move, themes, fd):
    comment = " ".join(sorted(themes.split())[:3]) if themes else "tactic"
    fd.write(f"# {pos_id}: {comment}\n")
    fd.write(f"Pos{pos_id} ; {fen} ; {best_move}\n")

def main():
    args = parse_args()
    target = args["count"]
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print(f"Downloading & filtering puzzles from:\n  {PUZZLE_URL}")
    print(f"Filters: rating [{args['min_rating']}-{args['max_rating']}], "
          f"popularity >= {args['min_popularity']}")
    print(f"Target: {target} puzzles")

    headers, reader = stream_csv_from_url(PUZZLE_URL)
    collected = []

    for i, row in enumerate(reader):
        if not row:
            continue
        if not passes_filter(row, headers, args):
            continue

        raw_fen = row[headers.index("FEN")]
        moves = row[headers.index("Moves")]
        parts = moves.split()
        opp_move_uci = parts[0]
        player_move_uci = parts[1]

        board = chess.Board(raw_fen)
        board.push_uci(opp_move_uci)
        puzzle_fen = board.fen()

        collected.append({
            "id": row[headers.index("PuzzleId")],
            "fen": puzzle_fen,
            "best_move": player_move_uci,
            "rating": row[headers.index("Rating")],
            "popularity": row[headers.index("Popularity")],
            "themes": row[headers.index("Themes")],
        })

        if len(collected) >= target:
            break

        if (i + 1) % 100000 == 0:
            print(f"  Scanned {i+1:,} rows, found {len(collected)}/{target}...")

    print(f"Scanned {i+1:,} rows total, found {len(collected)}/{target}")

    if not collected:
        print("ERROR: no puzzles matched filters. Try looser criteria.")
        return

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# Lichess puzzle benchmark -- auto-generated by fetch_lichess_puzzles.py\n")
        f.write("# Format: name ; FEN ; best_move (UCI)\n\n")
        for p in collected:
            comment_themes = " ".join(sorted(p["themes"].split())[:3]) if p["themes"] else "tactic"
            f.write(f"# {p['id']}: rating={p['rating']} pop={p['popularity']} | {comment_themes}\n")
            f.write(f"chess{p['id']} ; {p['fen']} ; {p['best_move']}\n")
            f.write("\n")

    print(f"\nExported {len(collected)} puzzles to:")
    print(f"  {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
